import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  // const SubmitForm = trpc.useQuery(["ingredient.hello", { text: "from tRPC" }]);
  const [name, setName] = React.useState("");
  const [quanity, setQuanity] = React.useState("");
  const [canBeUsedUp, setCanBeUsedUp] = React.useState(false);
  const [category, setCategory] = React.useState("");
  const submitForm = () => {
    console.log(name, quanity, canBeUsedUp, category);
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <form
          onSubmit={submitForm}
          className="w-full max-w-lg flex gap-2 flex-wrap"
        >
          <input
            type="text"
            className="border p-2"
            name="Name"
            placeholder="Name"
            onChange={(e) => setName(e.target.value)}
          />
          <input
            type="number"
            className="border p-2"
            name="Quantity"
            placeholder="Quantity"
            onChange={(e) => setQuanity(e.target.value)}
          />
          <div className="flex items-center gap-2">
            <label htmlFor="canBeUsedUp" className="ml-2">
              Can Be Used Up
            </label>
            <input
              type="checkbox"
              className="border p-2"
              id="canBeUsedUp"
              name="canBeUsedUp"
              onChange={(e) => setCanBeUsedUp(e.target.checked)}
            />
            <select onChange={(e) => setCategory(e.target.value)}>
              <option value="Dairy">Dairy</option>
              <option value="Meat">Meat</option>
              <option value="Bread">Bread</option>
              <option value="Vegetable">Vegetable</option>
            </select>
          </div>
          <button type="submit" className="border p-2">
            Submit
          </button>
        </form>
      </div>
    </>
  );
};

export default Home;
