import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ingredientRouter } from "../server/router/ingredient";
import { recipeRouter } from "../server/router/recipe";
import { trpc } from "../utils/trpc";
import Link from "next/link";
import ListOfIngredients from "./components/ListOfIngredients";

const Home: NextPage = () => {
  const utils = trpc.useContext();
  const allIngredients = trpc.useQuery(["ingredient.getAll"]);
  //const SubmitForm = trpc.useQuery(["ingredient.hello", { text: "from tRPC" }]);
  const mutateData = trpc.useMutation(["ingredient.createIngredient"], {
    async onSuccess() {
      await utils.invalidateQueries(["ingredient.getAll"]);
    },
  });
  const recipesAble = trpc.useQuery(["example.getRecipesAble"]);

  const [name, setName] = React.useState("");
  const [quanity, setQuanity] = React.useState(Number);
  const [canBeUsedUp, setCanBeUsedUp] = React.useState(false);
  const [category, setCategory] = React.useState("");
  //console.log(JSON.stringify(allIngredients));

  const submitForm = async () => {
    console.log(name, quanity, canBeUsedUp, category);

    const input = {
      name: name,
      quanity: quanity,
      canBeUsedUp: canBeUsedUp,
      category: category,
    };

    const returnState = mutateData.mutate({
      name,
      quanity,
      canBeUsedUp,
      category,
    });
  };

  return (
    <>
      <Head>
        <title>Thinking Pantry</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <form
          onSubmit={submitForm}
          className="w-full max-w-lg flex gap-2 flex-wrap"
        >
          <input
            type="text"
            className="border p-2"
            name="Name"
            placeholder="Name"
            onChange={(e) => setName(e.target.value)}
          />
          <input
            type="number"
            className="border p-2"
            name="Quantity"
            placeholder="Quantity"
            onChange={(e) => setQuanity(parseInt(e.target.value))}
          />
          <div className="flex items-center gap-2">
            <label htmlFor="canBeUsedUp" className="ml-2">
              Can Be Used Up
            </label>
            <input
              type="checkbox"
              className="border p-2"
              id="canBeUsedUp"
              name="canBeUsedUp"
              onChange={(e) => setCanBeUsedUp(e.target.checked)}
            />
            <select onChange={(e) => setCategory(e.target.value)}>
              <option value="Dairy">Dairy</option>
              <option value="Raw Meat">Raw Meat</option>
              <option value="Bread">Bread</option>
              <option value="Vegetable">Vegetable</option>
            </select>
          </div>
          <button type="submit" className="border p-2">
            Submit
          </button>
        </form>

        <div>
          <Link href="/ingredients">
            <a>List of Current Ingredients</a>
          </Link>

          <Link href="/recipes">
            <a>List of Current recipes</a>
          </Link>
        </div>
        <div>
          {" "}
          <p>{JSON.stringify(recipesAble)}</p>
        </div>
      </div>
      Test
      <ListOfIngredients></ListOfIngredients>
    </>
  );
};

export default Home;
